config/routes.rb
MusicCollabz::Application.routes.draw do
    devise_for :users,  
              path_names: {sign_in: "login", sign_out: "logout"},
              controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :listings
  resources :users

  authenticated :user do
    root :to => "listings#index"
  end
  
  match '/about',        to: 'static_pages#about'
  match '/home',         to: 'static_pages#home'
  match '/listings',     to: 'listings#index'
  match '/users/:id',    to: 'users#show'
  
  root :to => "static_pages#home"
  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :city, :description, :duration, :latitude, :longitude, :street, :email, :username, :price
	belongs_to :user
	
	validates :street, presence: true, length: { maximum: 40 }
	validates :price, presence: true, numericality: true, length: { maximum: 5}
	validates :description, length: { maximum: 140 }

	acts_as_gmappable
  def gmaps4rails_address
    "#{city}, #{street}"
  end

  def gmaps4rails_price 
  	"#{price}"
  end 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings, dependent: :destroy 
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
  validates_presence_of :username
  validates_uniqueness_of :username

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def after_sign_in_path_for(resource)
    current_user
	end
	def after_sign_up_path_for(resource)
    current_user
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
before_filter :authenticate_user!, only: [:create, :destroy, :edit, :new] 


	def index
		@body_id = "listings"
	  @listings = Listing.all
	  @mylisting = Listing.find_by_id(params[:id])
	  @json = @listings.to_gmaps4rails do |listing, marker|
	  	marker.infowindow render_to_string(partial: "infowindow", locals: {listing: listing})
	  	marker.title "#{listing.street}"
	  	marker.json({ price: listing.price })
	  	marker.picture({picture: view_context.image_path('parking.png'),
	  									width: 32,
	  									height: 40 }) 
		end
	end

	def show
    @user = User.find(params[:id])
		@listings = @user.listings()
    @listing = current_user.listings.build      
	end

	def new
		@listing = current_user.listings.build(params[:listing])
	end

	def create
		@listing = current_user.listings.build(params[:listing])
		if @listing.save
      flash[:success] = "Listing Created Successfully"
      redirect_to current_user
    else
      redirect_to current_user
      flash[:error] = "Street and Price must not be blank"
    end
	end

	def edit
		@user = User.find(params[:id])
		@listings = @user.listings()
		@listing = current_user.listings.build(params[:listing])
	end

	def update
		
	end

	def destroy
		@listing = Listing.find(params[:id])
		@listing.destroy
    redirect_to current_user
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      # flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	 @body_id = "home" 
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!
	
	def index
		@users = User.all
	end
	
	def show
    @user = User.find(params[:id])
		@listings = @user.listings()
    @listing = current_user.listings.build      
	end

	def create
		@listing = @user.listings.build()
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Parkit", root_path, class:"brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li id="fat-menu" class="dropdown">      
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.username %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Your Listing", current_user %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <li class="btn-after"><%= link_to "Find a Space", listings_path, class:"nav-btn btn-find" %></li> 
            <li class="btn-after"><%= link_to "List Your Space", new_listing_path, class:"nav-btn btn-list" %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li class="btn-after"><%= link_to "Find a Space", listings_path, class:"nav-btn btn-find" %></li> 
            <li class="btn-after"><%= link_to "List Your Space", new_user_registration_path, class:"nav-btn btn-list" %></li>
            <!-- <li><%= link_to "Sign in With Twitter", user_omniauth_authorize_path(:twitter) %></li> -->
          <% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parkit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body <%= " id=#{@body_id}" if @body_id %> >	
	<div id="wrap">
		<%= render 'shared/loadingDiv' %>
		<%= render 'layouts/header' %>
		<div id="content-bg">
			<div class="container content">
	      <% flash.each do |key, value| %>
	        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
	      <% end %>	      
				<div class="row">
					<%= yield %>
				</div>
			</div>
		</div>
		<div id="push"></div> 
	</div><!-- Close Wrap -->
	<div id="footer">
	  <div class="container">
	  	<p class="footer-links">
	  		<%= link_to "Home", root_path %>
	  		<%= link_to "About", about_path %>
	  		<%= link_to "How it Works", "#" %>
	  	</p>
	  </div>
	</div> 
	<%= yield :scripts %>
	<script>
	$(window).load(function() {
		$("#status").fadeOut();
		$("#preloader").delay(350).fadeOut("slow");
	})
	</script>
</body>
</html>

app/views/listings/_infowindow.html.erb
<p class="muted"><%= listing.street %>, <%= listing.city %></p>
<h3>$<%= listing.price %><small> /monthly</small></h3>
<p class="infowindow-btn"><%= mail_to listing.user.email, "Rent This Space", class: "btn btn-primary btn-block", target:"_blank", encode: "hex", subject:"Parkit Rental Inquiry: #{listing.street}, #{listing.city}"  %></p>

app/views/listings/_listing.html.erb
<li>
  <span class="content"><%= listing.city %> </span>
	<span class="content"><%= listing.street %> </span>
	<span class="content">$<%= listing.price %></span>

  <% if current_user %>
    <%= link_to "delete", listing, method: :delete,
                                     confirm: "You sure?",
                                     title: listing.street %>
  <% end %>
</li>

app/views/listings/edit.html.erb
<aside class="span4">
  <section>
  	<h3>Edit Your Listing</h3>
  	<%= render 'shared/listing_form' %>
  </section>
</aside>

app/views/listings/index.html.erb
<div class="span12">
  <div id="slider">
    <h5>Filter Listings by Price</h5>
    <div id='price-range' ></div>
    <input type="text" id="filtered-price"/>
  </div>

  <%= gmaps(map_options: { 
  					detect_location: false, 
  					center_on_user:  false,
  					center_latitude: 49.28186,
  					center_longitude: -123.122149,
  					disableDefaultUI: true,

  					zoom: 13 							},
  					markers: { data: @json }) 
  %>

  <script type="text/javascript">
    $(document).ready(function() {

      Gmaps.map.callback = function() {

        var PriceFilter = {
          min: 0,
          max: 500,
        };

        $( "#filtered-price" ).val( "$"+(PriceFilter.min)+ " - " + "$"+(PriceFilter.max))
        $("#price-range").slider({
          range: true,
          min: PriceFilter.min,
          max: PriceFilter.max,
          values: [ PriceFilter.min, PriceFilter.max ],
          slide: function(event, ui) {
            $( "#filtered-price" ).val("$"+(ui.values[ 0 ])+ " - " + "$"+(ui.values[ 1 ]))
            PriceFilter.min = ui.values[ 0 ]
            PriceFilter.max = ui.values[ 1 ]
            applyFilters()
          }
        });

        var VisibleMarkers = function() {
        var filtered = _.reject(Gmaps.map.markers, function(marker) {
            return marker.price < PriceFilter.min || marker.price > PriceFilter.max;
          });
          return filtered
         }

        var applyFilters = function() {
          _.each(Gmaps.map.markers, function(marker) {
            Gmaps.map.hideMarker(marker)
          })
          _.each(VisibleMarkers(), function(marker) {
            Gmaps.map.showMarker(marker)
          })
        };
     	}

  	});
  </script>
</div>

app/views/listings/new.html.erb
<div class="form">
  <section>
  	<h3>Add a Listing</h3>
  	<%= render 'shared/listing_form' %>
  </section>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_listing_form.html.erb
<%= form_for(@listing) do |f| %>
  <%= render 'shared/error_messages', object: @listing %> 
	<%= f.label :city %>
	<%= f.text_field :city, value: "Vancouver", readonly:"readonly", class:"input-block-level"%>

	<label for="listing_street">Street Address</label>
	<%= f.text_field :street , placeholder: "",class:"input-block-level" %>

	<label for="listing_price">Price <small>/monthly</small></label>
	<div class="input-prepend">
		<span class="add-on">$</span>
		<%= f.text_field :price, id:"appendedPrependedInput" %>
		<!-- <span class="add-on">/monthly</span> -->
	</div>

<!-- 	<%= f.label :description %>
	<%= f.text_area :description, rows:8, class:"input-block-level" %> -->

	<p><%= f.submit "Add Listing", class: "btn btn-block btn-primary" %></p>
<% end %>

app/views/shared/_loader.html.erb
<div id="display_ajax">
     <p><img src="ajax-loader.gif" /></p>
</div>

app/views/shared/_loadingDiv.html.erb
<div id="preloader">
	<div id="status"></div>
</div>

app/views/static_pages/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Parkzy", root_path, class:"brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">         
          <li><%= link_to "About", about_path %></li>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="span6" id="welcomeBlurb">
	<h1>Find and Rent Parking Space</h1>
	<p class="subhead">Parkit connects those who have unused parking space with those who need it most. </p>	
		<%= link_to listings_path, class: "btn btn-large btn-primary" do %>
			Find a Space 
		<% end %>
		<%= link_to new_user_registration_path, class: "btn btn-large btn-success" do %>
			List Your Space 
		<% end %>		
</div>

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="form">
  <section>
    <h3>Your Listing</h3>
    <% if @user.listings.any? %>
        <ul class="listings">
          <%= render @listings %> 
        </ul>
      <% else %>
      <p>No space listed. Get started now.</p>
      <%= link_to "List Your Space", new_listing_path , class: "btn btn-primary btn-block" %>
      <% end %>
  </section>
</div>

<!-- <div class="span8">
  <h3>My Listing</h3>
  <% if @user.listings.any? %>
    <ol class="listings">
      <%= render @listings %>
    </ol>
  <% end %>
</div> -->